import type { Metadata } from "next";
import { Bricolage } from "@/utils/fonts";
import { ThemeProvider } from "next-themes";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${Bricolage}`}>
        <ThemeProvider attribute={'class'}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
