FROM oven/bun:1.3.13-slim

LABEL type="frontend"

WORKDIR /src

COPY package.json bun.lock ./

COPY client/package.json ./client/

RUN bun install --filter ./client... --frozen-lockfile

# relative path
WORKDIR /src/client

COPY client .

# Build-time arguments
ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_FRONTEND_URL
ARG NEXT_PUBLIC_RAZORPAY_KEY_ID

# Expose them as environment variables for next build
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL
ENV NEXT_PUBLIC_RAZORPAY_KEY_ID=$NEXT_PUBLIC_RAZORPAY_KEY_ID

RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "start" ]
