FROM oven/bun:1.3.13-slim

LABEL type="backend"

WORKDIR /src

# copy root manifests
COPY package.json bun.lock ./

# this will create ./server directory to mirror like the local workspace
COPY server/package.json ./server/

# copy Prisma schema early (so `bun install` postinstall works)
COPY server/prisma ./server/prisma

# This installs only the workspace package named server and its dependencies, not the whole monorepo.
# why three dots? to install server and all workspace dependencies it relies on recursively.
# If the filtered install misses anything, fall back to a plain `bun install`.
RUN bun install --filter ./server... --frozen-lockfile

# now copy the rest of the server code
COPY server ./server

# switched directory to run further commands (absolute path)
WORKDIR /src/server

RUN bun run build

EXPOSE 4000

CMD [ "bun", "run", "start" ]
