name: "CI"

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install vercel CLI
        run: npm i -g vercel
      - name: server deployment
        run: vercel --prod --yes
        working-directory: ./server
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}